### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by fabiommendes** [lappis-unb/catalogo-minc#1]
# 0.x

* [ ] CRUD de projetos
* [ ] Estudos de interface

# Futuro
* [ ] Dataviz?
* [ ] QA para os softwares do catálogo?
* [ ] Direcionar comunidades
* [ ] Checklist automático?
